/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Colour;
import Model.Game;
import Model.Universe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.media.j3d.Canvas3D;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Jose
 */
public class ControlWindow extends JFrame {

    /**
     * Creates new form ControlWindow
     */
    private Universe universe;
    private Visualization ventana1, ventana2;
    private Timer whiteTimer, blackTimer;

    public ControlWindow(Canvas3D canvas, Universe universe) {
        
        super();    
        this.universe = universe;

        initComponents();
        setLocation (980, 0);
        addWindowListener(new WindowAdapter(){
          @Override
          public void windowClosing(WindowEvent e){
            closeApp(0);
          }
        });

        // Pocición de las ventana
        int posicion1[] = {0, 0};

       // Inicializamos la 1º ventana    
        ventana1 = new Visualization (this, false, canvas, posicion1);
        ventana1.setVisible(true);

        // Dejamos habilitado el toggle correspondiente a la cámara en perspectiva
        this.tgPerspective.setSelected(true);

        //
        //this.cbAxes.setSelected(true);

        // timers
        whiteTimer = new Timer(1000, new ActionListener(){ // cada 1000 ms se ejecuta
            int minutos = 15;
            int segundos = 0;

            public void actionPerformed(ActionEvent ev) { 
                if(segundos != 0 || minutos != 0){
                    lbWhiteTime.setText(minutos + ":" + segundos);

                    if(segundos == 0 && minutos != 0){
                        segundos = 60;
                        minutos--;
                    }

                    if(segundos != 0)
                        segundos--;
                    
                }else
                    Game.winner(Colour.Black);
            }
        });

        blackTimer = new Timer(1000, new ActionListener(){ // cada 1000 ms se ejecuta
            int minutos = 15;
            int segundos = 0;

            public void actionPerformed(ActionEvent ev) {
                if(segundos != 0 || minutos != 0){
                    lbBlackTime.setText(minutos + ":" + segundos);

                    if(segundos == 0 && minutos != 0){
                        segundos = 60;
                        minutos--;
                    }

                    if(segundos != 0)
                        segundos--;
                    
                }else
                    Game.winner(Colour.White);
            }
        });    

        // inicializamos el temporizador de las fichas blancas
        whiteTimer.start();

        pack();    
    }
  
    public void startWhiteTime(){
        whiteTimer.start();
    }

    public void stopWhiteTime(){
        whiteTimer.stop();
    }  
    
    public void startBlackTime(){
        blackTimer.start();
    }

    public void stopBlackTime(){
        blackTimer.stop();
    }      
    
    public void setTimeBlack(String text){
        this.lbBlackTime.setText(text);
    }
    
    public void setTimeWhite(String text){
        this.lbWhiteTime.setText(text);
    }    

    public void showWindow(){
      setVisible(true);
    }

    void closeApp(int code){
      universe.closeApp(code);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbAxes = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        tgPlan = new javax.swing.JToggleButton();
        tgPerspective = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbWhiteTime = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbBlackTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Axes"));

        cbAxes.setText("Axes");
        cbAxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAxesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAxes, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(cbAxes)
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("View"));

        tgPlan.setText("Plan");
        tgPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgPlanActionPerformed(evt);
            }
        });

        tgPerspective.setText("Perspective");
        tgPerspective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgPerspectiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tgPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tgPerspective)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgPlan)
                    .addComponent(tgPerspective))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Times Remaining"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("White"));

        lbWhiteTime.setText("15:0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbWhiteTime)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbWhiteTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Black"));

        lbBlackTime.setText("15:0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbBlackTime)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbBlackTime)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAxesActionPerformed
        // TODO add your handling code here:
        universe.showAxes (cbAxes.isSelected());
    }//GEN-LAST:event_cbAxesActionPerformed

    private void tgPerspectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgPerspectiveActionPerformed
        // TODO add your handling code here:
        if(tgPerspective.isSelected()){        
            if(tgPlan.isSelected())
                tgPlan.setSelected(false);           
            universe.enablePerspectiveView();
        }else{
            tgPerspective.setSelected(true);            
        }                    
    }//GEN-LAST:event_tgPerspectiveActionPerformed

    private void tgPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgPlanActionPerformed
        // TODO add your handling code here:
        if(tgPlan.isSelected()){
            if(tgPerspective.isSelected())
                tgPerspective.setSelected(false);           
            universe.enablePlanView();
        }else{
            tgPlan.setSelected(true);            
        }                            
    }//GEN-LAST:event_tgPlanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAxes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbBlackTime;
    private javax.swing.JLabel lbWhiteTime;
    private javax.swing.JToggleButton tgPerspective;
    private javax.swing.JToggleButton tgPlan;
    // End of variables declaration//GEN-END:variables
}
